import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-neutral-50 text-neutral-900 antialiased dark:bg-neutral-950 dark:text-neutral-100`}>
        <div className="min-h-dvh bg-[radial-gradient(40rem_40rem_at_120%_-10%,rgba(59,130,246,0.12),transparent),radial-gradient(32rem_32rem_at_-10%_10%,rgba(236,72,153,0.10),transparent)] dark:bg-[radial-gradient(40rem_40rem_at_120%_-10%,rgba(59,130,246,0.16),transparent),radial-gradient(32rem_32rem_at_-10%_10%,rgba(236,72,153,0.14),transparent)]">
          {children}
        </div>
      </body>
    </html>
  );
}
